CC = gcc
ASM = nasm
CFLAGS = -Wall -Wextra -std=c99 -m32
ASMFLAGS = -f macho32
LDFLAGS = -m32

all: area_calculator

area_calculator: main.o math_funcs.o funcs.o
    $(CC) $(LDFLAGS) -o $@ $^ -lm

main.o: main.c
    $(CC) $(CFLAGS) -c $<

math_funcs.o: math_funcs.c
    $(CC) $(CFLAGS) -c $<

funcs.o: funcs.asm
    $(ASM) $(ASMFLAGS) -o $@ $<

clean:
    rm -f *.o area_calculator